# Generated by Django 2.1.5 on 2019-11-15 12:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20191029_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='todolist',
            options={},
        ),
        migrations.AddField(
            model_name='todolist',
            name='picture',
            field=models.ImageField(blank=True, default='static/picture/No_image_3x4.svg.png', upload_to='static/picture/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='general', max_length=100),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default=datetime.datetime(2019, 11, 15, 12, 37, 46, 855721, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 18, 12, 37, 46, 855761, tzinfo=utc), null=True),
        ),
    ]
