# Generated by Django 2.1.5 on 2019-11-15 14:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20191115_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default=datetime.datetime(2019, 11, 15, 14, 4, 49, 905306, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 18, 14, 4, 49, 905345, tzinfo=utc), null=True),
        ),
    ]
