# Generated by Django 2.1.5 on 2019-12-01 14:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20191115_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default=datetime.datetime(2019, 12, 1, 14, 2, 53, 684231, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 4, 14, 2, 53, 684271, tzinfo=utc), null=True),
        ),
    ]
