# Generated by Django 2.1.5 on 2019-12-01 15:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0005_auto_20191201_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='polzovatel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default=datetime.datetime(2019, 12, 1, 15, 14, 11, 733040, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 4, 15, 14, 11, 733095, tzinfo=utc), null=True),
        ),
    ]
